version: "3.8"

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "2424:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - php
    networks:
      - webnet

  php:
    image: php:8.2-fpm
    container_name: php
    volumes:
      - ./nginx/html:/usr/share/nginx/html
    networks:
      - webnet

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: p4rv1zk44n
      MYSQL_DATABASE: casa_db
      MYSQL_USER: mearazor
      MYSQL_PASSWORD: p4rv1zk44n
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - webnet

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: mariadb
      MYSQL_ROOT_PASSWORD: p4rv1zk44n
    ports:
      - "8024:80"
    depends_on:
      - mariadb
    networks:
      - webnet

volumes:
  db_data:

networks:
  webnet:
